## Exploratory Data Analysis

Understanding the dataset to explore how the data is present and is there any need of transforming the dataset to our need.
1. Vendor Selection for profitability
2. Product Pricing Optimization

In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect("inventory.db")

In [3]:
tables = pd.read_sql_query("Select name from sqlite_master where type='table'", conn)
tables

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

In [4]:
for table in tables['name']:
    print(f"{"-" * 50} {table} {"-" * 50}")
    print(f"Count of records: ",pd.read_sql(f"select count(*) as count from {table}", conn)['count'].values[0])
    display(pd.read_sql(f"Select * from {table} limit 5", conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records:  206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records:  224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of records:  2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records:  12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of records:  12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records:  5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None


###### The purchases table contains actual purchase data, including the date of purchase, product (brands) purchased by vendors, the amount paid and the quantity purchased.
###### The purchase price column is derived from purchase_price table, which provide product-wise actual and purchase price. The combination of vendor and brand is unique.
###### The vendor_invoice table aggregates data from purchases table, summarizing quantity and amount, along with additional columns like freight. The table maintains uniquesness based on vendor and PO number.
###### The sales table captures actual sales transaction, detailing the brand purchased by vendors, the quantity sold, the selling price, and the revenue earned.

###### As the data we need for analysis is distributed in different tables, we need to create a summary table containing:
###### 1. purchase transactions made by vendors
###### 2. Sales transaction data
###### 3. freight cost for each vendor
###### 4. actual product price from vendors

In [5]:
vendor_invoice = pd.read_csv("data/vendor_invoice.csv")
sales = pd.read_csv("data/sales.csv")
purchases = pd.read_csv("data/purchases.csv")
purchase_prices = pd.read_csv("data/purchase_prices.csv")

In [6]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [7]:
freight_summary = pd.read_sql("Select vendorNumber, round(sum(freight),2) as FreightCost from vendor_invoice group by vendorNumber", conn)
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [8]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='object')

In [9]:
purchase_prices.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='object')

In [10]:
prices_summary = pd.read_sql(
    """ Select
            p.vendorNumber, 
            p.vendorName, 
            p.Brand,
            p.Description,
            p.PurchasePrice,
            pp.Volume,
            pp.Price as ActualPrice,
            sum(p.Quantity) as TotalPurchasedQuantity,
            sum(p.Dollars) as TotalPurchasedDollar
        from purchases p join purchase_prices pp on p.Brand = pp.Brand
        where p.purchasePrice > 0
        group by 1,2,3      
        order by 8                    
    """, conn)

prices_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchasedQuantity,TotalPurchasedDollar
0,54,AAPER ALCOHOL & CHEMICAL CO,990,Ethyl Alcohol 200 Proof,105.07,3750,134.49,1,105.07
1,480,BACARDI USA INC,4357,Bacardi Oakheart Spiced Trav,7.46,750,9.99,1,7.46
2,480,BACARDI USA INC,5181,Leblon Cedilla Acai Liqueur,23.99,750,29.99,1,23.99
3,480,BACARDI USA INC,6916,St Germain Liqueur,11.10,200,14.99,1,11.10
4,516,BANFI PRODUCTS CORP,17172,Riunite Sweet White,4.10,750,5.99,1,4.10
...,...,...,...,...,...,...,...,...,...
10687,10000,MAJESTIC FINE WINES,6570,Kendall Jackson Chard Vt RSV,6.77,750,10.99,215668,1460072.36
10688,3960,DIAGEO NORTH AMERICA INC,3606,Smirnoff Raspberry Vodka,0.74,50,0.99,226085,167302.90
10689,8004,SAZERAC CO INC,5111,Dr McGillicuddy's Mentholmnt,0.72,50,0.99,244654,176150.88
10690,3960,DIAGEO NORTH AMERICA INC,1892,Yukon Jack,0.72,50,0.99,254824,183473.28
10691,3960,DIAGEO NORTH AMERICA INC,8111,Smirnoff 80 Proof,0.77,50,0.99,337660,259998.20

In [11]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [12]:
sales_summary = pd.read_sql("""
    select
        vendorNo as VendorNumber,
        Brand,
        round(sum(SalesDollars), 2) as TotalSalesDollars,
        round(sum(SalesPrice), 2) as TotalSalesPrice,
        round(sum(SalesQuantity), 2) as TotalSalesQuantity,
        round(sum(ExciseTax),2 ) as TotalExcisetax           
    from sales
    group by 1, 2
    order by 3
""", conn)

sales_summary

,VendorNumber,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExcisetax
0,8004,5287,0.98,0.98,2.0,0.10
1,9206,2773,0.99,0.99,1.0,0.05
2,3252,3933,1.98,0.99,2.0,0.10
3,3924,9123,1.98,0.99,2.0,0.10
4,10050,3623,1.98,1.98,2.0,0.10
...,...,...,...,...,...,...
11267,3960,3545,4223107.62,545778.28,135838.0,249587.83
11268,3960,4261,4475972.88,420050.01,200412.0,368242.80
11269,17035,8068,4538120.60,461140.15,187140.0,343854.07
11270,4425,3405,4819073.49,561512.37,160247.0,294438.66
11271,1128,1233,5101919.51,672819.31,142049.0,260999.20

In [13]:
priceSalesSummary = pd.merge(prices_summary, sales_summary, left_on=["VendorNumber", "Brand"], right_on=["VendorNumber", "Brand"], how='left')

In [14]:
vendor_summary = pd.merge(priceSalesSummary, freight_summary, on="VendorNumber", how='left')

In [15]:
vendor_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchasedQuantity,TotalPurchasedDollar,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExcisetax,FreightCost
0,54,AAPER ALCOHOL & CHEMICAL CO,990,Ethyl Alcohol 200 Proof,105.07,3750,134.49,1,105.07,NaN,NaN,NaN,NaN,0.48
1,480,BACARDI USA INC,4357,Bacardi Oakheart Spiced Trav,7.46,750,9.99,1,7.46,399.60,369.63,40.0,31.58,89286.27
2,480,BACARDI USA INC,5181,Leblon Cedilla Acai Liqueur,23.99,750,29.99,1,23.99,89.97,89.97,3.0,2.37,89286.27
3,480,BACARDI USA INC,6916,St Germain Liqueur,11.10,200,14.99,1,11.10,374.75,314.79,25.0,5.25,89286.27
4,516,BANFI PRODUCTS CORP,17172,Riunite Sweet White,4.10,750,5.99,1,4.10,161.73,131.78,27.0,2.98,8510.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,10000,MAJESTIC FINE WINES,6570,Kendall Jackson Chard Vt RSV,6.77,750,10.99,215668,1460072.36,2326007.78,189608.96,214238.0,24083.77,17587.59
10688,3960,DIAGEO NORTH AMERICA INC,3606,Smirnoff Raspberry Vodka,0.74,50,0.99,226085,167302.90,223483.59,21764.16,225741.0,11842.95,257032.07
10689,8004,SAZERAC CO INC,5111,Dr McGillicuddy's Mentholmnt,0.72,50,0.99,244654,176150.88,239543.37,20941.47,241963.0,12692.41,50293.62
10690,3960,DIAGEO NORTH AMERICA INC,1892,Yukon Jack,0.72,50,0.99,254824,183473.28,250837.29,20741.49,253371.0,13295.86,257032.07
10691,3960,DIAGEO NORTH AMERICA INC,8111,Smirnoff 80 Proof,0.77,50,0.99,337660,259998.20,331589.61,21424.59,334939.0,17579.29,257032.07

In [ ]:
# vendor_sales_summary = pd.read_sql("""
#     with freightSummary as (
#         Select vendorNumber, round(sum(freight),2) as FreightCost from vendor_invoice group by vendorNumber
#     ),
#     PurchaseSummary as (
#         Select
#             p.vendorNumber, 
#             p.vendorName, 
#             p.Brand,
#             p.description,
#             p.PurchasePrice,
#             pp.Volume,
#             pp.Price as actualPrice,
#             sum(p.Quantity) as TotalPurchasedQuantity,
#             sum(p.Dollars) as TotalPurchasedDollar
#         from purchases p join purchase_prices pp on p.Brand = pp.Brand
#         where p.purchasePrice > 0
#         group by 1,2,3,4,5,6,7    
#     ),
#     salesSummary as (
#         select
#         vendorNo as vendorNumber,
#         Brand,
#         round(sum(SalesDollars), 2) as TotalSalesDollars,
#         round(sum(SalesPrice), 2) as TotalSalesPrice,
#         round(sum(SalesQuantity), 2) as TotalSalesQuantity,
#         round(sum(ExciseTax),2 ) as TotalExcisetax           
#     from sales
#     group by 1, 2                      
#     )
#     select
#         ps.vendorNumber,
#         ps.VendorName, 
#         ps.Brand,
#         ps.Description,
#         ps.PurchasePrice,
#         ps.Volume,
#         ps.actualPrice,
#         ps.TotalPurchasedQuantity,
#         ps.TotalPurchasedDollar,
#         ss.TotalSalesDollars,
#         ss.TotalSalesPrice,
#         ss.TotalSalesQuantity,
#         ss.TotalExcisetax,
#         fs.FreightCost
#     from PurchaseSummary ps left join SalesSummary ss on ps.vendorNumber = ss.vendorNumber and ps.Brand = ss.Brand
#     left join FreightSummary fs on fs.vendorNumber = ps.vendorNumber
#     order by ps.TotalPurchasedDollar desc
# """, conn)

In [17]:
# vendor_sales_summary

,vendorNumber,vendorName,Brand,description,PurchasePrice,Volume,actualPrice,TotalPurchasedQuantity,TotalPurchasedDollar,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExcisetax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,1750,36.99,145080,3811251.60,5101919.51,672819.31,142049.0,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,1750,28.99,164038,3804041.22,4819073.49,561512.37,160247.0,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,1750,24.99,187407,3418303.68,4538120.60,461140.15,187140.0,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,1750,22.99,201682,3261197.94,4475972.88,420050.01,200412.0,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,1750,29.99,138109,3023206.01,4223107.62,545778.28,135838.0,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,750,4.99,2,2.64,15.95,10.96,5.0,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,50,0.49,6,2.34,65.66,1.47,134.0,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,50,0.99,2,1.48,1.98,0.99,2.0,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,200,1.99,1,1.47,143.28,77.61,72.0,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,50,0.99,1,0.71,85.14,33.66,86.0,4.46,38994.78

###### Here, vendor_summary and vendor_sales_summary are same, just 2 different approaches to summarize all 3 tables into 1. We will use Vendor Summary.

This query generates a vendor-wise sales and purchase summary.
1. This query resolves heavy joins and aggregations on large dataset like purchase and sales.
2. Storing this resultant dataset for faster Dashboarding and reporting.

### Cleaning Vendor_summary data

In [18]:
vendor_summary.dtypes

VendorNumber                int64
VendorName                 object
Brand                       int64
Description                object
PurchasePrice             float64
Volume                     object
ActualPrice               float64
TotalPurchasedQuantity      int64
TotalPurchasedDollar      float64
TotalSalesDollars         float64
TotalSalesPrice           float64
TotalSalesQuantity        float64
TotalExcisetax            float64
FreightCost               float64
dtype: object

In [19]:
vendor_summary.isnull().sum()       
# here, 178 means there are such cases where vendor couldn't sell those products which  he bought earlier.

VendorNumber                0
VendorName                  0
Brand                       0
Description                 0
PurchasePrice               0
Volume                      0
ActualPrice                 0
TotalPurchasedQuantity      0
TotalPurchasedDollar        0
TotalSalesDollars         178
TotalSalesPrice           178
TotalSalesQuantity        178
TotalExcisetax            178
FreightCost                 0
dtype: int64

In [20]:
vendor_summary['Volume'] = vendor_summary['Volume'].astype("float")

In [21]:
vendor_summary['VendorName'].unique()

array(['AAPER ALCOHOL & CHEMICAL CO', 'BACARDI USA INC            ',
       'BANFI PRODUCTS CORP        ', 'STATE WINE & SPIRITS   ',
       'SAZERAC NORTH AMERICA INC. ', 'BROWN-FORMAN CORP          ',
       'CONSTELLATION BRANDS INC   ', 'VINEYARD BRANDS INC        ',
       'DIAGEO CHATEAU ESTATE WINES', 'VRANKEN AMERICA            ',
       'Circa Wines                ', 'ALISA CARR BEVERAGES           ',
       'SOUTHERN WINE & SPIRITS NE ', 'DJINN SPIRITS LLC          ',
       'EDRINGTON AMERICAS         ', 'E & J GALLO WINERY         ',
       'WILLIAM GRANT & SONS INC   ', 'HEAVEN HILL DISTILLERIES   ',
       'DIAGEO NORTH AMERICA INC   ', 'MARTIGNETTI COMPANIES',
       'KOBRAND CORPORATION        ', 'MILTONS DISTRIBUTING CO    ',
       'MHW LTD                    ', 'PALM BAY INTERNATIONAL INC ',
       'PINE STATE TRADING CO      ', 'PROXIMO SPIRITS INC.       ',
       'R.P.IMPORTS INC            ', 'SAZERAC CO INC             ',
       'LUXCO INC                  ', 'STE MICHELLE WINE ESTATES  ',
       'ULTRA BEVERAGE COMPANY LLP ', 'M S WALKER INC             ',
       'FREDERICK WILDMAN & SONS   ', 'WINE GROUP INC             ',
       'PERFECTA WINES             ', 'JIM BEAM BRANDS COMPANY    ',
       'PERNOD RICARD USA          ', 'Dunn Wine Brokers          ',
       'FORTUNE WINE BROKERS LLC   ', 'THE IMPORTED GRAPE LLC     ',
       'VINILANDIA USA             ', 'THE PIERPONT GROUP LLC     ',
       'CRUSH WINES                ', 'FLAVOR ESSENCE INC         ',
       'OLE SMOKY DISTILLERY LLC   ', 'REMY COINTREAU USA INC     ',
       'MOET HENNESSY USA INC      ', 'FLAG HILL WINERY & VINEYARD',
       'Serralles Usa LLC          ', 'DUGGANS DISTILLED PRODUCTS ',
       'STAR INDUSTRIES INC.       ', 'STOLI GROUP,(USA) LLC      ',
       'CAPSTONE INTERNATIONAL     ', 'DISARONNO INTERNATIONAL LLC',
       'TREASURY WINE ESTATES      ', 'ADAMBA IMPORTS INTL INC    ',
       'LATITUDE BEVERAGE COMPANY  ', 'MARSALLE COMPANY           ',
       'MCCORMICK DISTILLING CO    ', 'UNCORKED       ',
       'PARK STREET IMPORTS LLC    ', 'SHAW ROSS INT L IMP LTD    ',
       'PHILLIPS PRODUCTS CO.      ', 'MAJESTIC FINE WINES        ',
       'CAMPARI AMERICA            ', 'STELLAR IMPORTING CO LLC   ',
       'SURVILLE ENTERPRISES CORP  ',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'SEA HAGG DISTILLERY LLC    ', 'TRINCHERO FAMILY ESTATES   ',
       'WESTERN SPIRITS BEVERAGE CO', 'BULLY BOY DISTILLERS       ',
       'CASTLE BRANDS CORP.        ', 'SOUTHERN GLAZERS W&S OF NE ',
       'ALTAMAR BRANDS LLC         ', 'BRONCO WINE COMPANY        ',
       'DELICATO VINEYARDS INC     ', 'HIGHLAND WINE MERCHANTS LLC',
       'PSP WINES ', 'WEIN BAUER INC             ',
       'VINEXTRA INC               ', 'KLIN SPIRITS LLC           ',
       'HOOD RIVER DISTILLERS, Inc.', 'SEA BREEZE CELLARS LLC     ',
       'SILVER MOUNTAIN CIDERS     ', 'TY KU LLC                  ',
       'Russian Standard Vodka     ', 'POVERTY LANE ORCHARDS      ',
       'VINEYARD BRANDS LLC        ', 'CHARLES JACQUIN ET CIE INC ',
       'LAIRD & CO                 ', 'TRUETT HURST               ',
       'FANTASY FINE WINES CORP    ', 'BLACK PRINCE DISTILLERY INC',
       'TAMWORTH DISTILLING        ', 'LAUREATE IMPORTS CO        ',
       'CENTEUR IMPORTS LLC        ', 'ATLANTIC IMPORTING COMPANY ',
       'MOONLIGHT MEADERY          ', 'AMERICAN SPIRITS EXCHANGE  ',
       'CALEDONIA SPIRITS INC      ', 'SIDNEY FRANK IMPORTING CO  ',
       'BLACK ROCK SPIRITS LLC     ', 'MARTIGNETTI COMPANIES ',
       'TAKARA SAKE USA INC        ', 'APPOLO VINEYARDS LLC       ',
       'SWEETWATER FARM         ', 'VINEDREA WINES LLC         ',
       'WALPOLE MTN VIEW WINERY    ', 'NICHE W & S                ',
       'LOYAL DOG WINERY           ', 'GILMANTON WINERY & VINEYARD',
       'PREMIER DISTRIBUTORS       ', 'SMOKY QUARTZ DISTILLERY LLC',
       'LABELLE VYDS AND WINERY    ', 'HAUNTING WHISPER VYDS      ',
       'INCREDIBREW INC            ', 'FULCHINO VINEYARD INC      ',
       'JEWELL TOWNE VINEYARDS     ', 'TALL SHIP DISTILLERY LLC   ',
       'CANDIA VINEYARDS           ', 'BLACK COVE BEVERAGES       ',
       'ZORVINO VINEYARDS          ', 'STARK BREWING COMPANY      ',
       'FABRIZIA SPIRITS LLC       ', 'PREMIUM PORT WINES, INC.   ',
       'SWEET BABY VINEYARD        ', 'AMERICAN VINTAGE BEVERAGE  ',
       'MANGO BOTTLING INC         '], dtype=object)

In [22]:
vendor_summary["VendorName"] = vendor_summary["VendorName"].apply(lambda x: x.strip())

In [23]:
vendor_summary['VendorName'].unique()

array(['AAPER ALCOHOL & CHEMICAL CO', 'BACARDI USA INC',
       'BANFI PRODUCTS CORP', 'STATE WINE & SPIRITS',
       'SAZERAC NORTH AMERICA INC.', 'BROWN-FORMAN CORP',
       'CONSTELLATION BRANDS INC', 'VINEYARD BRANDS INC',
       'DIAGEO CHATEAU ESTATE WINES', 'VRANKEN AMERICA', 'Circa Wines',
       'ALISA CARR BEVERAGES', 'SOUTHERN WINE & SPIRITS NE',
       'DJINN SPIRITS LLC', 'EDRINGTON AMERICAS', 'E & J GALLO WINERY',
       'WILLIAM GRANT & SONS INC', 'HEAVEN HILL DISTILLERIES',
       'DIAGEO NORTH AMERICA INC', 'MARTIGNETTI COMPANIES',
       'KOBRAND CORPORATION', 'MILTONS DISTRIBUTING CO', 'MHW LTD',
       'PALM BAY INTERNATIONAL INC', 'PINE STATE TRADING CO',
       'PROXIMO SPIRITS INC.', 'R.P.IMPORTS INC', 'SAZERAC CO INC',
       'LUXCO INC', 'STE MICHELLE WINE ESTATES',
       'ULTRA BEVERAGE COMPANY LLP', 'M S WALKER INC',
       'FREDERICK WILDMAN & SONS', 'WINE GROUP INC', 'PERFECTA WINES',
       'JIM BEAM BRANDS COMPANY', 'PERNOD RICARD USA',
       'Dunn Wine Brokers', 'FORTUNE WINE BROKERS LLC',
       'THE IMPORTED GRAPE LLC', 'VINILANDIA USA',
       'THE PIERPONT GROUP LLC', 'CRUSH WINES', 'FLAVOR ESSENCE INC',
       'OLE SMOKY DISTILLERY LLC', 'REMY COINTREAU USA INC',
       'MOET HENNESSY USA INC', 'FLAG HILL WINERY & VINEYARD',
       'Serralles Usa LLC', 'DUGGANS DISTILLED PRODUCTS',
       'STAR INDUSTRIES INC.', 'STOLI GROUP,(USA) LLC',
       'CAPSTONE INTERNATIONAL', 'DISARONNO INTERNATIONAL LLC',
       'TREASURY WINE ESTATES', 'ADAMBA IMPORTS INTL INC',
       'LATITUDE BEVERAGE COMPANY', 'MARSALLE COMPANY',
       'MCCORMICK DISTILLING CO', 'UNCORKED', 'PARK STREET IMPORTS LLC',
       'SHAW ROSS INT L IMP LTD', 'PHILLIPS PRODUCTS CO.',
       'MAJESTIC FINE WINES', 'CAMPARI AMERICA',
       'STELLAR IMPORTING CO LLC', 'SURVILLE ENTERPRISES CORP',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'SEA HAGG DISTILLERY LLC',
       'TRINCHERO FAMILY ESTATES', 'WESTERN SPIRITS BEVERAGE CO',
       'BULLY BOY DISTILLERS', 'CASTLE BRANDS CORP.',
       'SOUTHERN GLAZERS W&S OF NE', 'ALTAMAR BRANDS LLC',
       'BRONCO WINE COMPANY', 'DELICATO VINEYARDS INC',
       'HIGHLAND WINE MERCHANTS LLC', 'PSP WINES', 'WEIN BAUER INC',
       'VINEXTRA INC', 'KLIN SPIRITS LLC', 'HOOD RIVER DISTILLERS, Inc.',
       'SEA BREEZE CELLARS LLC', 'SILVER MOUNTAIN CIDERS', 'TY KU LLC',
       'Russian Standard Vodka', 'POVERTY LANE ORCHARDS',
       'VINEYARD BRANDS LLC', 'CHARLES JACQUIN ET CIE INC', 'LAIRD & CO',
       'TRUETT HURST', 'FANTASY FINE WINES CORP',
       'BLACK PRINCE DISTILLERY INC', 'TAMWORTH DISTILLING',
       'LAUREATE IMPORTS CO', 'CENTEUR IMPORTS LLC',
       'ATLANTIC IMPORTING COMPANY', 'MOONLIGHT MEADERY',
       'AMERICAN SPIRITS EXCHANGE', 'CALEDONIA SPIRITS INC',
       'SIDNEY FRANK IMPORTING CO', 'BLACK ROCK SPIRITS LLC',
       'TAKARA SAKE USA INC', 'APPOLO VINEYARDS LLC', 'SWEETWATER FARM',
       'VINEDREA WINES LLC', 'WALPOLE MTN VIEW WINERY', 'NICHE W & S',
       'LOYAL DOG WINERY', 'GILMANTON WINERY & VINEYARD',
       'PREMIER DISTRIBUTORS', 'SMOKY QUARTZ DISTILLERY LLC',
       'LABELLE VYDS AND WINERY', 'HAUNTING WHISPER VYDS',
       'INCREDIBREW INC', 'FULCHINO VINEYARD INC',
       'JEWELL TOWNE VINEYARDS', 'TALL SHIP DISTILLERY LLC',
       'CANDIA VINEYARDS', 'BLACK COVE BEVERAGES', 'ZORVINO VINEYARDS',
       'STARK BREWING COMPANY', 'FABRIZIA SPIRITS LLC',
       'PREMIUM PORT WINES, INC.', 'SWEET BABY VINEYARD',
       'AMERICAN VINTAGE BEVERAGE', 'MANGO BOTTLING INC'], dtype=object)

In [24]:
vendor_summary.fillna(value=0, inplace=True)

In [25]:
vendor_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchasedQuantity,TotalPurchasedDollar,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExcisetax,FreightCost
0,54,AAPER ALCOHOL & CHEMICAL CO,990,Ethyl Alcohol 200 Proof,105.07,3750.0,134.49,1,105.07,0.00,0.00,0.0,0.00,0.48
1,480,BACARDI USA INC,4357,Bacardi Oakheart Spiced Trav,7.46,750.0,9.99,1,7.46,399.60,369.63,40.0,31.58,89286.27
2,480,BACARDI USA INC,5181,Leblon Cedilla Acai Liqueur,23.99,750.0,29.99,1,23.99,89.97,89.97,3.0,2.37,89286.27
3,480,BACARDI USA INC,6916,St Germain Liqueur,11.10,200.0,14.99,1,11.10,374.75,314.79,25.0,5.25,89286.27
4,516,BANFI PRODUCTS CORP,17172,Riunite Sweet White,4.10,750.0,5.99,1,4.10,161.73,131.78,27.0,2.98,8510.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,10000,MAJESTIC FINE WINES,6570,Kendall Jackson Chard Vt RSV,6.77,750.0,10.99,215668,1460072.36,2326007.78,189608.96,214238.0,24083.77,17587.59
10688,3960,DIAGEO NORTH AMERICA INC,3606,Smirnoff Raspberry Vodka,0.74,50.0,0.99,226085,167302.90,223483.59,21764.16,225741.0,11842.95,257032.07
10689,8004,SAZERAC CO INC,5111,Dr McGillicuddy's Mentholmnt,0.72,50.0,0.99,244654,176150.88,239543.37,20941.47,241963.0,12692.41,50293.62
10690,3960,DIAGEO NORTH AMERICA INC,1892,Yukon Jack,0.72,50.0,0.99,254824,183473.28,250837.29,20741.49,253371.0,13295.86,257032.07
10691,3960,DIAGEO NORTH AMERICA INC,8111,Smirnoff 80 Proof,0.77,50.0,0.99,337660,259998.20,331589.61,21424.59,334939.0,17579.29,257032.07

Creating new columns for better analysis.

In [35]:
vendor_summary["GrossProfit"] = (vendor_summary["TotalSalesDollars"] - vendor_summary['TotalPurchasedDollar']).round(2)

In [38]:
vendor_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchasedQuantity,TotalPurchasedDollar,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExcisetax,FreightCost,GrossProfit,ProfitMargin,StockTurnOver,SalesToPurchaseRatio
0,54,AAPER ALCOHOL & CHEMICAL CO,990,Ethyl Alcohol 200 Proof,105.07,3750.0,134.49,1,105.07,0.00,0.00,0.0,0.00,0.48,-105.07,-inf,0.000000,0.00
1,480,BACARDI USA INC,4357,Bacardi Oakheart Spiced Trav,7.46,750.0,9.99,1,7.46,399.60,369.63,40.0,31.58,89286.27,392.14,98.13,40.000000,53.57
2,480,BACARDI USA INC,5181,Leblon Cedilla Acai Liqueur,23.99,750.0,29.99,1,23.99,89.97,89.97,3.0,2.37,89286.27,65.98,73.34,3.000000,3.75
3,480,BACARDI USA INC,6916,St Germain Liqueur,11.10,200.0,14.99,1,11.10,374.75,314.79,25.0,5.25,89286.27,363.65,97.04,25.000000,33.76
4,516,BANFI PRODUCTS CORP,17172,Riunite Sweet White,4.10,750.0,5.99,1,4.10,161.73,131.78,27.0,2.98,8510.41,157.63,97.46,27.000000,39.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,10000,MAJESTIC FINE WINES,6570,Kendall Jackson Chard Vt RSV,6.77,750.0,10.99,215668,1460072.36,2326007.78,189608.96,214238.0,24083.77,17587.59,865935.42,37.23,0.993369,1.59
10688,3960,DIAGEO NORTH AMERICA INC,3606,Smirnoff Raspberry Vodka,0.74,50.0,0.99,226085,167302.90,223483.59,21764.16,225741.0,11842.95,257032.07,56180.69,25.14,0.998478,1.34
10689,8004,SAZERAC CO INC,5111,Dr McGillicuddy's Mentholmnt,0.72,50.0,0.99,244654,176150.88,239543.37,20941.47,241963.0,12692.41,50293.62,63392.49,26.46,0.989001,1.36
10690,3960,DIAGEO NORTH AMERICA INC,1892,Yukon Jack,0.72,50.0,0.99,254824,183473.28,250837.29,20741.49,253371.0,13295.86,257032.07,67364.01,26.86,0.994298,1.37
10691,3960,DIAGEO NORTH AMERICA INC,8111,Smirnoff 80 Proof,0.77,50.0,0.99,337660,259998.20,331589.61,21424.59,334939.0,17579.29,257032.07,71591.41,21.59,0.991942,1.28

In [30]:
vendor_summary['ProfitMargin'] = (vendor_summary['GrossProfit']/vendor_summary['TotalSalesDollars']*100).round(2)

In [32]:
vendor_summary['StockTurnOver'] = vendor_summary['TotalSalesQuantity'] / vendor_summary['TotalPurchasedQuantity']

In [37]:
vendor_summary['SalesToPurchaseRatio'] = (vendor_summary['TotalSalesDollars'] / vendor_summary["TotalPurchasedDollar"]).round(2)

#### Now, creating a table to store the cleaned dataset into the database.

In [39]:
cursor = conn.cursor()

In [42]:
vendor_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'Volume', 'ActualPrice', 'TotalPurchasedQuantity',
       'TotalPurchasedDollar', 'TotalSalesDollars', 'TotalSalesPrice',
       'TotalSalesQuantity', 'TotalExcisetax', 'FreightCost', 'GrossProfit',
       'ProfitMargin', 'StockTurnOver', 'SalesToPurchaseRatio'],
      dtype='object')

In [43]:
cursor.execute("""
    create table vendor_summary (
        VendorNumber int,
        vendorName varchar(100),
        Brand int,
        Description varchar(100),
        PurchasePrice decimal(10,2),
        ActualPrice decimal(10, 2),
        Volume decimal(10, 2),
        TotalPurchaseQuantity int,
        TotalPurchasedDollar decimal(15,2),
        TotalSalesDollars decimal(15,2),
        TotalSalesPrice decimal(15,2),
        TotalSalesQuantity decimal(15,2),
        TotalExcisetax decimal(15,2),
        FreightCost decimal(15,2),
        GrossProfit decimal(15,2),
        ProfitMargin decimal(15,2),
        StockTurnOver decimal(15,2),
        SalesToPurchaseRatio decimal(15,2),
        PRIMARY KEY (VendorNumber, Brand)
    )
""")

In [44]:
pd.read_sql("select * from vendor_summary",conn)        # successfully created table in the database.

Empty DataFrame
Columns: [VendorNumber, vendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchasedDollar, TotalSalesDollars, TotalSalesPrice, TotalSalesQuantity, TotalExcisetax, FreightCost, GrossProfit, ProfitMargin, StockTurnOver, SalesToPurchaseRatio]
Index: []

In [45]:
# Now inserting data in the created table

vendor_summary.to_sql("vendor_summary", conn, if_exists="replace", index=False)

10692

In [46]:
pd.read_sql("select * from vendor_summary",conn)        # Successfully, inserted all the data in the sql table.

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchasedQuantity,TotalPurchasedDollar,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExcisetax,FreightCost,GrossProfit,ProfitMargin,StockTurnOver,SalesToPurchaseRatio
0,54,AAPER ALCOHOL & CHEMICAL CO,990,Ethyl Alcohol 200 Proof,105.07,3750.0,134.49,1,105.07,0.00,0.00,0.0,0.00,0.48,-105.07,-inf,0.000000,0.00
1,480,BACARDI USA INC,4357,Bacardi Oakheart Spiced Trav,7.46,750.0,9.99,1,7.46,399.60,369.63,40.0,31.58,89286.27,392.14,98.13,40.000000,53.57
2,480,BACARDI USA INC,5181,Leblon Cedilla Acai Liqueur,23.99,750.0,29.99,1,23.99,89.97,89.97,3.0,2.37,89286.27,65.98,73.34,3.000000,3.75
3,480,BACARDI USA INC,6916,St Germain Liqueur,11.10,200.0,14.99,1,11.10,374.75,314.79,25.0,5.25,89286.27,363.65,97.04,25.000000,33.76
4,516,BANFI PRODUCTS CORP,17172,Riunite Sweet White,4.10,750.0,5.99,1,4.10,161.73,131.78,27.0,2.98,8510.41,157.63,97.46,27.000000,39.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,10000,MAJESTIC FINE WINES,6570,Kendall Jackson Chard Vt RSV,6.77,750.0,10.99,215668,1460072.36,2326007.78,189608.96,214238.0,24083.77,17587.59,865935.42,37.23,0.993369,1.59
10688,3960,DIAGEO NORTH AMERICA INC,3606,Smirnoff Raspberry Vodka,0.74,50.0,0.99,226085,167302.90,223483.59,21764.16,225741.0,11842.95,257032.07,56180.69,25.14,0.998478,1.34
10689,8004,SAZERAC CO INC,5111,Dr McGillicuddy's Mentholmnt,0.72,50.0,0.99,244654,176150.88,239543.37,20941.47,241963.0,12692.41,50293.62,63392.49,26.46,0.989001,1.36
10690,3960,DIAGEO NORTH AMERICA INC,1892,Yukon Jack,0.72,50.0,0.99,254824,183473.28,250837.29,20741.49,253371.0,13295.86,257032.07,67364.01,26.86,0.994298,1.37
10691,3960,DIAGEO NORTH AMERICA INC,8111,Smirnoff 80 Proof,0.77,50.0,0.99,337660,259998.20,331589.61,21424.59,334939.0,17579.29,257032.07,71591.41,21.59,0.991942,1.28